// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import LinkableProperty from '../../axon/js/LinkableProperty.js';
import waveInterference from './waveInterference.js';

type StringsType = {
  'wave-interference': {
    'title': string;
    'titleStringProperty': LinkableProperty<string>;
  };
  'screen': {
    'waves': string;
    'wavesStringProperty': LinkableProperty<string>;
    'interference': string;
    'interferenceStringProperty': LinkableProperty<string>;
    'slits': string;
    'slitsStringProperty': LinkableProperty<string>;
    'diffraction': string;
    'diffractionStringProperty': LinkableProperty<string>;
  };
  'frequency': string;
  'frequencyStringProperty': LinkableProperty<string>;
  'diameter': string;
  'diameterStringProperty': LinkableProperty<string>;
  'eccentricity': string;
  'eccentricityStringProperty': LinkableProperty<string>;
  'amplitude': string;
  'amplitudeStringProperty': LinkableProperty<string>;
  'graph': string;
  'graphStringProperty': LinkableProperty<string>;
  'waterLevel': string;
  'waterLevelStringProperty': LinkableProperty<string>;
  'waterLevelAtCenter': string;
  'waterLevelAtCenterStringProperty': LinkableProperty<string>;
  'pressure': string;
  'pressureStringProperty': LinkableProperty<string>;
  'electricField': string;
  'electricFieldStringProperty': LinkableProperty<string>;
  'electricFieldAtCenter': string;
  'electricFieldAtCenterStringProperty': LinkableProperty<string>;
  'playTone': string;
  'playToneStringProperty': LinkableProperty<string>;
  'pressureAtCenter': string;
  'pressureAtCenterStringProperty': LinkableProperty<string>;
  'positionCM': string;
  'positionCMStringProperty': LinkableProperty<string>;
  'positionNM': string;
  'positionNMStringProperty': LinkableProperty<string>;
  'cmValue': string;
  'cmValueStringProperty': LinkableProperty<string>;
  'nmValue': string;
  'nmValueStringProperty': LinkableProperty<string>;
  'mmValue': string;
  'mmValueStringProperty': LinkableProperty<string>;
  'degreesValue': string;
  'degreesValueStringProperty': LinkableProperty<string>;
  'min': string;
  'minStringProperty': LinkableProperty<string>;
  'max': string;
  'maxStringProperty': LinkableProperty<string>;
  'centimetersUnits': string;
  'centimetersUnitsStringProperty': LinkableProperty<string>;
  'nanometersUnits': string;
  'nanometersUnitsStringProperty': LinkableProperty<string>;
  'secondsUnits': string;
  'secondsUnitsStringProperty': LinkableProperty<string>;
  'millisecondsUnits': string;
  'millisecondsUnitsStringProperty': LinkableProperty<string>;
  'femtosecondsUnits': string;
  'femtosecondsUnitsStringProperty': LinkableProperty<string>;
  'millisecondConversion': string;
  'millisecondConversionStringProperty': LinkableProperty<string>;
  'femtosecondConversion': string;
  'femtosecondConversionStringProperty': LinkableProperty<string>;
  'screenLabel': string;
  'screenLabelStringProperty': LinkableProperty<string>;
  'intensity': string;
  'intensityStringProperty': LinkableProperty<string>;
  'topView': string;
  'topViewStringProperty': LinkableProperty<string>;
  'sideView': string;
  'sideViewStringProperty': LinkableProperty<string>;
  'distanceUnits': string;
  'distanceUnitsStringProperty': LinkableProperty<string>;
  'timeUnits': string;
  'timeUnitsStringProperty': LinkableProperty<string>;
  'normal': string;
  'normalStringProperty': LinkableProperty<string>;
  'slow': string;
  'slowStringProperty': LinkableProperty<string>;
  'top': string;
  'topStringProperty': LinkableProperty<string>;
  'separation': string;
  'separationStringProperty': LinkableProperty<string>;
  'noBarrier': string;
  'noBarrierStringProperty': LinkableProperty<string>;
  'oneSlit': string;
  'oneSlitStringProperty': LinkableProperty<string>;
  'twoSlits': string;
  'twoSlitsStringProperty': LinkableProperty<string>;
  'time': string;
  'timeStringProperty': LinkableProperty<string>;
  'slitWidth': string;
  'slitWidthStringProperty': LinkableProperty<string>;
  'width': string;
  'widthStringProperty': LinkableProperty<string>;
  'height': string;
  'heightStringProperty': LinkableProperty<string>;
  'circleDiameter': string;
  'circleDiameterStringProperty': LinkableProperty<string>;
  'rotation': string;
  'rotationStringProperty': LinkableProperty<string>;
  'squareWidth': string;
  'squareWidthStringProperty': LinkableProperty<string>;
  'latticeSpacing': string;
  'latticeSpacingStringProperty': LinkableProperty<string>;
  'disorder': string;
  'disorderStringProperty': LinkableProperty<string>;
  'slitSeparation': string;
  'slitSeparationStringProperty': LinkableProperty<string>;
  'waves': string;
  'wavesStringProperty': LinkableProperty<string>;
  'particles': string;
  'particlesStringProperty': LinkableProperty<string>;
  'both': string;
  'bothStringProperty': LinkableProperty<string>;
  'waterWaveGenerator': string;
  'waterWaveGeneratorStringProperty': LinkableProperty<string>;
  'soundGenerator': string;
  'soundGeneratorStringProperty': LinkableProperty<string>;
  'lightGenerator': string;
  'lightGeneratorStringProperty': LinkableProperty<string>;
  'soundEffect': string;
  'soundEffectStringProperty': LinkableProperty<string>;
  'none': string;
  'noneStringProperty': LinkableProperty<string>;
  'lots': string;
  'lotsStringProperty': LinkableProperty<string>;
};

const WaveInterferenceStrings = getStringModule( 'WAVE_INTERFERENCE' ) as StringsType;

waveInterference.register( 'WaveInterferenceStrings', WaveInterferenceStrings );

export default WaveInterferenceStrings;
