// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import type LocalizedStringProperty from '../../chipper/js/LocalizedStringProperty.js';
import waveInterference from './waveInterference.js';

type StringsType = {
  'wave-interference': {
    'title': string;
    'titleStringProperty': LocalizedStringProperty;
  };
  'screen': {
    'waves': string;
    'wavesStringProperty': LocalizedStringProperty;
    'interference': string;
    'interferenceStringProperty': LocalizedStringProperty;
    'slits': string;
    'slitsStringProperty': LocalizedStringProperty;
    'diffraction': string;
    'diffractionStringProperty': LocalizedStringProperty;
  };
  'frequency': string;
  'frequencyStringProperty': LocalizedStringProperty;
  'diameter': string;
  'diameterStringProperty': LocalizedStringProperty;
  'eccentricity': string;
  'eccentricityStringProperty': LocalizedStringProperty;
  'amplitude': string;
  'amplitudeStringProperty': LocalizedStringProperty;
  'graph': string;
  'graphStringProperty': LocalizedStringProperty;
  'waterLevel': string;
  'waterLevelStringProperty': LocalizedStringProperty;
  'waterLevelAtCenter': string;
  'waterLevelAtCenterStringProperty': LocalizedStringProperty;
  'pressure': string;
  'pressureStringProperty': LocalizedStringProperty;
  'electricField': string;
  'electricFieldStringProperty': LocalizedStringProperty;
  'electricFieldAtCenter': string;
  'electricFieldAtCenterStringProperty': LocalizedStringProperty;
  'playTone': string;
  'playToneStringProperty': LocalizedStringProperty;
  'pressureAtCenter': string;
  'pressureAtCenterStringProperty': LocalizedStringProperty;
  'positionCM': string;
  'positionCMStringProperty': LocalizedStringProperty;
  'positionNM': string;
  'positionNMStringProperty': LocalizedStringProperty;
  'cmValue': string;
  'cmValueStringProperty': LocalizedStringProperty;
  'nmValue': string;
  'nmValueStringProperty': LocalizedStringProperty;
  'mmValue': string;
  'mmValueStringProperty': LocalizedStringProperty;
  'degreesValue': string;
  'degreesValueStringProperty': LocalizedStringProperty;
  'min': string;
  'minStringProperty': LocalizedStringProperty;
  'max': string;
  'maxStringProperty': LocalizedStringProperty;
  'centimetersUnits': string;
  'centimetersUnitsStringProperty': LocalizedStringProperty;
  'nanometersUnits': string;
  'nanometersUnitsStringProperty': LocalizedStringProperty;
  'secondsUnits': string;
  'secondsUnitsStringProperty': LocalizedStringProperty;
  'millisecondsUnits': string;
  'millisecondsUnitsStringProperty': LocalizedStringProperty;
  'femtosecondsUnits': string;
  'femtosecondsUnitsStringProperty': LocalizedStringProperty;
  'millisecondConversion': string;
  'millisecondConversionStringProperty': LocalizedStringProperty;
  'femtosecondConversion': string;
  'femtosecondConversionStringProperty': LocalizedStringProperty;
  'screenLabel': string;
  'screenLabelStringProperty': LocalizedStringProperty;
  'intensity': string;
  'intensityStringProperty': LocalizedStringProperty;
  'topView': string;
  'topViewStringProperty': LocalizedStringProperty;
  'sideView': string;
  'sideViewStringProperty': LocalizedStringProperty;
  'distanceUnits': string;
  'distanceUnitsStringProperty': LocalizedStringProperty;
  'timeUnits': string;
  'timeUnitsStringProperty': LocalizedStringProperty;
  'normal': string;
  'normalStringProperty': LocalizedStringProperty;
  'slow': string;
  'slowStringProperty': LocalizedStringProperty;
  'top': string;
  'topStringProperty': LocalizedStringProperty;
  'separation': string;
  'separationStringProperty': LocalizedStringProperty;
  'noBarrier': string;
  'noBarrierStringProperty': LocalizedStringProperty;
  'oneSlit': string;
  'oneSlitStringProperty': LocalizedStringProperty;
  'twoSlits': string;
  'twoSlitsStringProperty': LocalizedStringProperty;
  'time': string;
  'timeStringProperty': LocalizedStringProperty;
  'slitWidth': string;
  'slitWidthStringProperty': LocalizedStringProperty;
  'width': string;
  'widthStringProperty': LocalizedStringProperty;
  'height': string;
  'heightStringProperty': LocalizedStringProperty;
  'circleDiameter': string;
  'circleDiameterStringProperty': LocalizedStringProperty;
  'rotation': string;
  'rotationStringProperty': LocalizedStringProperty;
  'squareWidth': string;
  'squareWidthStringProperty': LocalizedStringProperty;
  'latticeSpacing': string;
  'latticeSpacingStringProperty': LocalizedStringProperty;
  'disorder': string;
  'disorderStringProperty': LocalizedStringProperty;
  'slitSeparation': string;
  'slitSeparationStringProperty': LocalizedStringProperty;
  'waves': string;
  'wavesStringProperty': LocalizedStringProperty;
  'particles': string;
  'particlesStringProperty': LocalizedStringProperty;
  'both': string;
  'bothStringProperty': LocalizedStringProperty;
  'waterWaveGenerator': string;
  'waterWaveGeneratorStringProperty': LocalizedStringProperty;
  'soundGenerator': string;
  'soundGeneratorStringProperty': LocalizedStringProperty;
  'lightGenerator': string;
  'lightGeneratorStringProperty': LocalizedStringProperty;
  'soundEffect': string;
  'soundEffectStringProperty': LocalizedStringProperty;
  'none': string;
  'noneStringProperty': LocalizedStringProperty;
  'lots': string;
  'lotsStringProperty': LocalizedStringProperty;
};

const WaveInterferenceStrings = getStringModule( 'WAVE_INTERFERENCE' ) as StringsType;

waveInterference.register( 'WaveInterferenceStrings', WaveInterferenceStrings );

export default WaveInterferenceStrings;
