// Copyright 2018, University of Colorado Boulder

/**
 * A wave can either be generated by a point source (POINT) or by a plane wave (PLANE).
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( require => {
  'use strict';

  // modules
  const Enumeration = require( 'PHET_CORE/Enumeration' );
  const waveInterference = require( 'WAVE_INTERFERENCE/waveInterference' );

  return waveInterference.register( 'WaveSpatialTypeEnum', new Enumeration( [ 'POINT', 'PLANE' ] ) );
} );