// Copyright 2018-2026, University of Colorado Boulder

/**
 * Valid values for the spatial type of a wave. A wave can be generated by a point source ('point') or by a plane
 * wave ('plane').
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
export const WaveSpatialTypeValues = [ 'point', 'plane' ] as const;

/**
 * Represents whether the wave is generated from a point source or as a plane wave.
 */
export type WaveSpatialType = typeof WaveSpatialTypeValues[number];
