// Copyright 2018, University of Colorado Boulder

//REVIEW A nit about doc for most (all?) enums. You say "Determines whether..." but an enum determines nothing, it is a
// set of values with no responsibilities. A {Property.<WaveSpatialType>} would "determine".
//REVIEW* Updated, please review.
/**
 * A wave can either be generated by a point source (POINT) or by a plane wave (PLANE).
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
define( require => {
  'use strict';

  // modules
  const Enumeration = require( 'PHET_CORE/Enumeration' );
  const waveInterference = require( 'WAVE_INTERFERENCE/waveInterference' );

  return waveInterference.register( 'WaveSpatialType', new Enumeration( [ 'POINT', 'PLANE' ] ) );
} );